@startuml

title Application

class Application {
    +USERS ArrayList<User> {static}
    +MOVIES ArrayList<Movie> {static}
}

class Transaction {
    -tID: int
    -date: Date
    -user: User
    -movie: Movie
}

class Movie {
    -mID: int
    -title: String
    -GENRE: ArrayList<Genres>
    -year: int
    -price: double
}

enum Genres

enum Countries

@enduml