@startuml Usecase Overview
title Video On Demand System Use Cases

skinparam actorStyle awesome
skinparam packageStyle rectangle

actor User as "User"
actor Buyer as "Buyer"
actor Seller as "Seller"

rectangle "Common User Actions" as UserMgmt {
    (Register)
    (Login)
    (Logout)
    (viewUser)
    (viewTransactions)
    (viewInventory)
    (viewMovie)
    (updateUser)
    (deleteUser)
}

rectangle {
  Buyer -- (addToCart)
  Buyer -- (removeFromCart)
  Buyer -- (viewCart)
  Buyer -- (checkout)
  (checkout) .r.> (viewCart) : <<include>>
}

rectangle {
  Seller -- (addMovie)
  Seller -- (removeMovie)
  Seller -- (updateMovie)
  (updateMovie) <.. (viewMovie) : <<extend>>
}

User -d- UserMgmt
User <|-r-- Seller
User <|-l-- Buyer

@enduml
